"""Base classes for sections (the pages in the carousel) and their actions."""
from __future__ import annotations

from dataclasses import dataclass, field
from typing import Callable, Protocol

import pygame.surface


class SectionContext(Protocol):
    """What sections receive when their action handlers fire.

    Kept as a Protocol so we don't import the App class here (cycles).
    """

    def show_result(self, title: str, text: str) -> None: ...
    def run_streaming(self, title: str, argv: list[str]) -> None: ...
    def show_cctv(self) -> None: ...
    def show_pingsweep(self) -> None: ...
    def show_arpscan(self) -> None: ...
    def show_wifi(self) -> None: ...
    def show_camscan(self) -> None: ...
    def show_wifi_attack(self) -> None: ...
    def show_eviltwin(self) -> None: ...
    def show_games(self) -> None: ...
    def show_captures(self) -> None: ...
    def show_loot_gallery(self) -> None: ...
    def show_scan_history(self) -> None: ...
    def show_web_access(self) -> None: ...
    def show_phone_camera(self) -> None: ...
    def show_diagnostics(self) -> None: ...
    def show_background_tasks(self) -> None: ...
    def show_tracker_history(self) -> None: ...
    def show_breach_check(self) -> None: ...
    def show_subdomain_enum(self) -> None: ...
    def show_user_pivot(self) -> None: ...
    def show_exif_inspector(self) -> None: ...
    def show_honeypot(self) -> None: ...
    def show_trackers(self) -> None: ...
    def show_probe_sniffer(self) -> None: ...
    def show_beacon_flood(self) -> None: ...
    def show_karma_lite(self) -> None: ...
    def show_wifi_multi_tool(self) -> None: ...
    def show_cracker(self) -> None: ...
    def show_data_sniper(self) -> None: ...
    def show_pmkid_sniper(self) -> None: ...
    def show_media_player(self) -> None: ...
    def show_tv(self) -> None: ...
    def show_youtube(self) -> None: ...
    def show_tailscale(self) -> None: ...
    def show_anonsurf(self) -> None: ...
    def show_vault(self) -> None: ...
    def show_bettercap(self) -> None: ...
    def show_mail(self) -> None: ...
    def show_messenger(self) -> None: ...
    def show_signal_scraper(self) -> None: ...
    def show_adsb(self) -> None: ...
    def show_pager(self) -> None: ...
    def show_foxhunter(self) -> None: ...
    def show_mission_report(self) -> None: ...
    def show_ghost_mode(self) -> None: ...
    def show_handshake_manager(self) -> None: ...
    def show_ragnar(self, phase: str = "landing") -> None: ...
    def show_traffic_cam(self) -> None: ...
    def show_camera_interceptor(self) -> None: ...
    def show_wifite(self) -> None: ...
    def show_wardrive(self) -> None: ...
    def show_chat(self) -> None: ...
    def show_sherlock(self, username: str) -> None: ...
    def show_deaddrop(self) -> None: ...
    def show_bbs(self) -> None: ...
    def show_ble_chat(self) -> None: ...
    def show_onion_chat(self) -> None: ...
    def show_ble_spam(self) -> None: ...
    def show_terminal(self) -> None: ...
    def show_theme_manager(self) -> None: ...
    def show_shop(self) -> None: ...
    def show_update(self, title: str, argv: list[str]) -> None: ...
    def show_menu(self, title: str, actions: list[tuple[str, Callable[[], None]]]) -> None: ...
    def get_input(self, title: str, callback: Callable[[str | None], None], initial: str = "") -> None: ...
    def go_back(self) -> None: ...
    def toast(self, msg: str) -> None: ...
    def play_notification(self) -> None: ...


@dataclass
class Action:
    label: str
    handler: Callable[[SectionContext], None] | None = None
    description: str = ""


@dataclass
class Section:
    title: str
    actions: list[Action] = field(default_factory=list)
    icon: str = ""   # short string drawn beside title in the tab bar
    icon_img: pygame.surface.Surface | None = None
    background_img: pygame.surface.Surface | None = None  # full page bg

    # Hooks — override in subclasses if needed.
    def on_enter(self, ctx: SectionContext) -> None: ...
    def on_leave(self, ctx: SectionContext) -> None: ...
